### PR TITLE
Update HESAE_REFSOURCE_STCM.csv

### PR DESCRIPTION
**Pull request by teenwyman**
Hi @adelmestri 

I have updated the HESAE_REFSOURCE_STCM.csv.
However, there are a few maps I am not quite sure about and I would like to ask for your advice. 

- 01-Self referral
Please correct me if I am wrong.
I interpret 01-Self referral as no referral. 
I am not sure if [8584](https://athena.ohdsi.org/search-terms/terms/8584) is the best one as it has a "is-a" relationship of "Outpatient Visit". 

- 02-Local authority social services
- 03-Emergency services
I don't know which one ([581381](https://athena.ohdsi.org/search-terms/terms/581381) or [8782](https://athena.ohdsi.org/search-terms/terms/8782)) is best for 03-Emergency services
- 06-Police
I can't find any standard visit concepts representing 06-Police. I leave it as 0, tentatively. I will remove it from the STCM if no target concept is found.
- 07-Health care provider

### CODE REVIEW

**Review by adelmestri — CHANGES_REQUESTED** [review]
01 "Self referral" is a referral: it means a patients went to A&E by himself, as it happens frequently. However, I do not think 8584 is the correct concept as it means "Mobile Unit".
Moreover, I am not sure the OHDSI advice to use the VISIT DOMAIN for this field is correct either. Could you ask Albert for advice on this please? He might have some suggestions. Thanks

**Comment by teenwyman** [comment]
Hi @adelmestri  Thank you for your reply. 

I updated to leave 01 "Self referral" as 0, tentatively (like what I did with 06-Police), as I can't find any suitable standard visit concepts for it. 

I don't know why the OHDSI designs using Visit Domain concepts for this data field, but it is what it is.
And honestly, I don't think we can "NOT FOLLOW" the rules at this moment. We can raise our concern to the OHDSI community ONLY.  
Albert is on holiday. I messaged him privately. Let's see if he can answer us shortly.

In addition, can you explain the meaning of 03-Emergency services to me?
Does it refer to A&E [581381](https://athena.ohdsi.org/search-terms/terms/581381) or ANY emergency services [8782](https://athena.ohdsi.org/search-terms/terms/8782)?

Thank you.

**Comment by adelmestri** [comment]
Hi Teen,

I think Albert would be able to answer better than me to your questions, as I have not worked in an A&E department.
I would wait for him answers as we cannot spend so much time on a secondary piece of information.
For the time being I will not use these codes for A&E mapping as the concepts do not seem to match well.
We can add them later if we find a good solution
Thanks

Best wishes,
Antonella
-------------------------------------------------------------
Dr Antonella Delmestri
Alan Turing Fellow
Lead Health Data Scientist
Botnar Research Centre
Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences
University of Oxford
Tel: 01865-223434
Web page: https://www.ndorms.ox.ac.uk/team/antonella-delmestri

**Comment by teenwyman** [comment]
Noted and thank you.

**Comment by teenwyman** [comment]
Hi @adelmestri noted and thank you.

**Comment by adelmestri** [comment]
Thanks all, I agree. I will remove this STCM file from the happing as these codes are not mapped well in the VISIT domain

**Pull request closed without merging**
