### PR TITLE
Ncras

### PR DESCRIPTION
**Pull request by teenwyman**
- updated the data fields in ncras treatment and tumour
- comment out the creation of pk_treatment as the following reason: 
image
- added 'tbl_ncras': ['tumour', 'treatment'] in __postgres_db_conf.py

Remark:
- No curation was done due to the absence of SQL.
- source._records count aligns with the count in the document

### CODE REVIEW

**Review by teenwyman — COMMENTED** [review]
I double checked the source data. 
Duplication exists if I added (eventdate, eventcode, opcs4_code) to the PK (e_patid, e_cr_patid, e_cr_id, eventdate, eventcode, opcs4_code).

image

image

**Review by adelmestri — APPROVED** [review]
The duplication aspect is worring as we cannot say if they did 3 IM or 1 recorded 3 times. Thanks for checking

**Comment by teenwyman** [comment]
> The duplication aspect is worring as we cannot say if they did 3 IM or 1 recorded 3 times. Thanks for checking

@adelmestri We can use distinct, like what I did in GOLD, during mapping to eliminate duplication.

**Comment by adelmestri** [comment]
My point is that we do not know if they are genuine duplications or if the data miss details that would differentiate the records. This can make a big difference in health economics where they count the costs

Best wishes,
Antonella
-------------------------------------------------------------
Dr Antonella Delmestri
Alan Turing Fellow
Lead Health Data Scientist
Botnar Research Centre
Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences
University of Oxford
Tel: 01865-223434
Web page: https://www.ndorms.ox.ac.uk/team/antonella-delmestri

**Pull request merged**
