### PR TITLE
Update 4_map_source_in_chunk.py

### PR DESCRIPTION
**Pull request by teenwyman**
Removed the CDM minor version in the insert SQL to cdm_source as it will fail to run the DQD. 
Will update it once OHDSI fixed the bug. 

FYI @Mandickel

### CODE REVIEW

**Review by adelmestri — CHANGES_REQUESTED** [review]
1. lower function is not necessary as we are managing numbers.
2. Also, it would be safer to use >= '5.4'  (instead of ++) so it will cover future versions

**Comment by teenwyman** [comment]
I have updated the code as you suggested, @adelmestri

**Review by adelmestri — APPROVED** [review]
I am not sure if the space between "cdm_version" and "[0:3]" could create problems.

**Comment by teenwyman** [comment]
> I am not sure if the space between "cdm_version" and "[0:3]" could create problems.

I tested it without any problems with the space. However, it would be great if you could remove the space for me, such that I do not have to create another pull request. Thank you. @adelmestri

**Comment by teenwyman** [comment]
@adelmestri @Mandickel 
the CDM minor version will fail to run the **Achilles** not DQD. I will update the comment in the code later.

**Pull request merged**
